### ISSUE TITLE
Emulate serial port

### ISSUE THREAD

**Issue by philpem** [philpem/freebee#1]
The emulator currently doesn't support the UNIX PC's onboard serial port.

It would be useful to have this, perhaps terminating in a PTY.

**Comment by agentbooth** [comment]
@philpem @arnoldrobbins After some struggling to understand how the interrupts and interrupt modes work with the 8274, I made some progress on this and can now login on a PTY -- it's pretty damn cool!  I also tried umodem upload out of the 3b1 and was able to download with xmodem.  I'll check this in once I get things more buttoned up.

**Comment by arnoldrobbins** [comment]
@philpem @agentbooth With 569a6230f7f38d8c9d4b33b309574f756b8ad176 merged in, this issue could be closed, no?  :-)  Thanks.

**Comment by philpem** [comment]
Yep, looks like we're sorted! Closing as fixed :)
