### ISSUE TITLE
Smarter hard disk image support (header?)

### ISSUE THREAD

**Issue by philpem** [philpem/freebee#10]
The hard disk image is currently a raw binary file.

It may be useful to add a header to this file to store the disk geometry, or a more structured format. This would allow for cylinder, head and sector range checking in the WD2010 driver.

The format could be organised as a header, followed by a sequence of numbered tracks, each containing numbered sectors. These would be appended to the file when a `FORMAT TRACK` command was sent to the WD2010.

Optionally the hard disk image data could be compressed, a la MAME's CHD format. This could be on a track-wise or sector-wise scale. The disadvantage is that this would be more complex to read and write, and may require an "overlay" file to store deltas.

**Comment by philpem** [comment]
A trailer might be a better option.

* If the hard disc file doesn't exist, one is created.
  * The disc geometry is set in the config file when this happens.
* Once the disc image has been created, the geometry in the config file is only used if there is no valid trailer block. (so raw dd images could still be used)

Using a trailer would still allow the use of tools like dd to work on the filesystem.

**Comment by arnoldrobbins** [comment]
Once formatted by the diagnostic disk, the hard disk has a header describing the geometry. With the merge of PR #29 the code reads that header and handles the geometry correctly.  I think this issue can be closed!  :-)  Thanks.
