### ISSUE TITLE
please don't use sed in makefile

### ISSUE THREAD

**Issue by tenox7** [philpem/freebee#21]
```
$ make
expr: syntax error
sed: 1: "s|@@compiler@@|clang: w ...": unescaped newline inside substitute pattern
make[1]: *** [versionheader] Error 1
make: *** [all] Error 2
```

replacing sed with gnu-sed

```
$ make
expr: syntax error
gsed: -e expression #6, char 69: unterminated `s' command
make[1]: *** [versionheader] Error 1
make: *** [all] Error 2
```

**Comment by philpem** [comment]
The problem is you're building with Clang, which has different version output to GCC. In all honesty this stuff can go, so I've removed it from the master branch.

Can you pull and rebuild (ideally cleanly) and see if this fixes your problem?

**Comment by tenox7** [comment]
Hi!

Thanks for your response! It looks much better now.

However this time I’m getting:

src/main.c:5:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~


Checked man pages on Linux, FreeBSD and macOS, for malloc() you only include <stdlib.h>

Regards
Antoni

**Comment by philpem** [comment]
Fixed! Try now?

**Comment by tenox7** [comment]
src/tc8250.c:3:10: fatal error: 'malloc.h' file not found
src/wd2010.c:3:10: fatal error: 'malloc.h' file not found
src/wd279x.c:3:10: fatal error: 'malloc.h' file not found
src/state.c:3:10: fatal error: 'malloc.h' file not found

src/main.c:247:5: error: conflicting types for 'SDL_main'
int main(void)
    ^
/usr/local/include/SDL/SDL_main.h:54:14: note: expanded from macro 'main'
#define main    SDL_main
                ^
/usr/local/include/SDL/SDL_main.h:57:22: note: previous declaration is here
extern C_LINKAGE int SDL_main(int argc, char *argv[]);
                     ^
1 error generated.
make[1]: *** [obj/main.o] Error 1
make: *** [all] Error 2


Also when cloning with recursive I’m gettin this error:

fatal: clone of 'git@github.com:kstenerud/Musashi.git' into submodule path '/Users/tenox/Code/freebee/src/musashi' failed
Failed to clone 'src/musashi'. Retry scheduled
Cloning into '/Users/tenox/Code/freebee/src/musashi'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:kstenerud/Musashi.git' into submodule path '/Users/tenox/Code/freebee/src/musashi' failed
Failed to clone 'src/musashi' a second time, aborting


I fixed it by going in to freebee/src and doing git clone of https://github.com/kstenerud/Musashi.git <https://github.com/kstenerud/Musashi.git> there. But just wanted to let you know that this happens.

Antoni

**Comment by philpem** [comment]
@tenox7 can you give the latest git HEAD a try?

I've removed a bunch of the versioning stuff and fixed the submodule URL.

Can you also tell me what version of SDL you're compiling against? Please run these two commands:

```
$ sdl-config --version
$ sdl2-config --version
```

And what platform are you building on? Operating system and compiler versions would be very useful.

**Comment by tenox7** [comment]
sorry for slow response, I'm on a Mac, 10.15.5. 

```
mac:/Users/tenox/Code> sdl-config --version
1.2.15
mac:/Users/tenox/Code> sdl2-config --version
2.0.12
```

**Comment by tenox7** [comment]
hi looks like this is solved, I have pulled down master head and everything builds cleanly (well with warnings but it works). Thanks a lot 👍
