### ISSUE TITLE
no SDL output on macOS

### ISSUE THREAD

**Issue by tenox7** [philpem/freebee#23]
```
mac:/Users/tenox/Code> sdl-config --version
1.2.15
mac:/Users/tenox/Code> sdl2-config --version
2.0.12
```

built latest version from head, the emulator starts and you can see it reading the disk:

```
mac:/Users/tenox/Code/freebee> ./freebee                                                       
FreeBee: A Quick-and-Dirty AT&T 3B1 Emulator. Version 0.0. (git c88db4c), debug mode.
Copyright (C) 2010 P. A. Pemberton. All rights reserved.
Licensed under the Apache License Version 2.0.
Musashi M680x0 emulator engine developed by Karl Stenerud <kstenerud@gmail.com>

Set 720x348 at 32 bits-per-pixel mode

ERROR loading disc image 'discim'.
src/wd2010.c:81:wd2010_init(): WD2010 initialised, 1040 cylinders, 8 heads, 16 sectors per track
Disc image loaded.
unhandled write16, addr=0x00E50004, data=0x00000018
unhandled write16, addr=0x00E50006, data=0x00000018
unhandled write16, addr=0x00E50004, data=0x000000F0
unhandled write16, addr=0x00E50006, data=0x000000F0
KBD WR 00 => 0300
KBD WR 00 => 9500
unhandled write16, addr=0x00E44000, data=0x00008000
unhandled write16, addr=0x00E45000, data=0x00008000
unhandled write16, addr=0x00E60000, data=0x00000001
unhandled write16, addr=0x00E60000, data=0x00000000
unhandled write16, addr=0x00490000, data=0x00004000
unhandled write16, addr=0x00491000, data=0x00004000
unhandled write16, addr=0x00494000, data=0x00000000
unhandled write16, addr=0x00495000, data=0x00000000
unhandled write16, addr=0x00493000, data=0x00004000
unhandled write16, addr=0x00497000, data=0x00004000
unhandled write16, addr=0x004F0000, data=0x00000000
unhandled write08, addr=0x004B0400, data=0x00000000
unhandled write08, addr=0x004B0800, data=0x00000000
src/wd2010.c:358:wd2010_write_reg(): WD2010: READ SECTOR cmd=20 chs=0:0:0 nsectors=1
src/wd2010.c:393:wd2010_write_reg(): 	READ lba = 0
src/wd2010.c:399:wd2010_write_reg(): 	READ len=512, pos=0, ssz=512
src/wd2010.c:169:wd2010_read_data(): WD2010: read done
src/wd2010.c:358:wd2010_write_reg(): WD2010: READ SECTOR cmd=20 chs=0:0:1 nsectors=0
src/wd2010.c:393:wd2010_write_reg(): 	READ lba = 512
src/wd2010.c:399:wd2010_write_reg(): 	READ len=512, pos=0, ssz=512
src/wd2010.c:169:wd2010_read_data(): WD2010: read done
```

However in the SDL window there is nothing:

![image](https://user-images.githubusercontent.com/8151602/93455442-361c6b80-f891-11ea-9cfa-1a32d59249ca.png)

Thanks :)

**Comment by philpem** [comment]
Is this the same Mac you used on #21 -- with Mac OS 10.15.5 (Catalina)?

It seems like this is a bug in SDL which manifests on Mojave and later: https://hg.libsdl.org/SDL/rev/ab7529cb9558

Seems like SDL2 has had a fix for this since 2018: https://hg.libsdl.org/SDL/rev/55489adbb75c

Can you try building and installing the latest development version of SDL1.2?

EDIT: Longer term Freebee should probably be ported to SDL2 but that's not a trivial task due to the API changes.

**Comment by agentbooth** [comment]
I believe 1.2.15 is already the latest SDL

**Comment by classilla** [comment]
Drive-by comment: this is an issue with SDL 1.2 on 10.14+ because Tutti is similarly affected. I don't know of a workaround.

**Comment by philpem** [comment]
Sorry if I wasn't clear - I was referring to building from the SDL source code in the Mercurial repository.

It seems like porting to SDL2 might fix it. I had a quick look at doing that, but it's not simple. Quite a bit of the API has changed...

**Comment by tenox7** [comment]
I will try that

**Comment by agentbooth** [comment]
Phil, I did a basic migration to SDL2. Would you like to migrate to SDL2? Or retain the 1.2 compatibility?

**Comment by philpem** [comment]
@shadyjesse My understanding is that SDL1.2 is deprecated at this point, so migrating to SDL2 is probably a good idea!

Submit a PR and I'll take a look. I had a go at it myself but got stuck migrating the SDL_Timer stuff to SDL2.

**Comment by agentbooth** [comment]
@philpem I just checked on Raspberry Pi and worked fine. PR has been submitted.

**Comment by philpem** [comment]
I've just merged @shadyjesse's SDL2 port. @tenox7 can you please confirm whether this fixes your issue?

**Comment by tenox7** [comment]
oh yes now it works thank you!
![image](https://user-images.githubusercontent.com/8151602/97144366-8bb22680-1721-11eb-9c87-9dc8212333fd.png)

I'm not sure if these bus error page not mapped are of any importance?

**Comment by philpem** [comment]
The bus errors are just debugging information from the memory handler - at some point they need to be turned off...

Glad to hear it works now!

Closed - resolved.

**Comment by tenox7** [comment]
thanks for fixing this! :)
