### ISSUE TITLE
Unix 3.51m kernel panics on large disk

### ISSUE THREAD

**Issue by arnoldrobbins** [philpem/freebee#30]
I have a large disk image (1400 cylinders x 16 heads x 17 sectors per track). I installed FIXDISK 2.0 and I get a kernel panic upon boot as shown in the attached screen shot.
![kernel-panic](https://user-images.githubusercontent.com/5863181/103436671-108c5580-4c27-11eb-95d5-e15682f5042e.png)

**Comment by arnoldrobbins** [comment]
I have made a disk image available [here](https://www.skeeve.com/big-disk.img.gz).  The FIXDISK2.0+IN file lives in /y. Install it and then upon reboot you should get the panic.  This should save you time in setting up a disk image for testing. Thanks!

**Comment by philpem** [comment]
That's strange. I have a few questions...

How was this disk formatted?
Which Diagnostics disk did you use, and what CHS settings?

Have you tried reproducing this on a disk with fewer cylinders or heads?
What is the smallest cylinder/head combination which causes this issue?

Have you tried 16 sectors per track?

**Comment by agentbooth** [comment]
With the latest code taking geometry from hd.img, I am having trouble loading hd.img's that are detected as 17 sectors per track. Ones detected as 16 sectors per track work fine, but 17 sectors per track will not boot. When I used 17 spt previously, I would load the image with `wd2010_init(..., 512, 16, 8)` [**16** spt, not 17].  Maybe this is problem and not 3.51m ?

**Comment by agentbooth** [comment]
Also, in `wd2010_init()`, this line:
`ctx->data[drivenum] = malloc(secsz * spt);`
should probably now be:
`ctx->data[drivenum] = malloc(ctx->geometry[drivenum].geom_secsz * ctx->geometry[drivenum].geom_spt);`

**Comment by philpem** [comment]
I'd agree with that change, Jesse.

**Comment by arnoldrobbins** [comment]
> How was this disk formatted?
> Which Diagnostics disk did you use, and what CHS settings?

I used the regular diagnostic disk. I would have chosen "other" and then 1400 cylinders, 16 heads, 17 sectors per track.

> Have you tried reproducing this on a disk with fewer cylinders or heads?
> What is the smallest cylinder/head combination which causes this issue?

I haven't tried to reproduce yet with different settings. I will put some time into it this evening, but I hardly know what to try first.  Probably fewer heads first.

> With the latest code taking geometry from hd.img, I am having trouble loading hd.img's that are detected as 17 sectors per track. Ones detected as 16 sectors per track work fine, but 17 sectors per track will not boot. When I used 17 spt previously, I would load the image with `wd2010_init(..., 512, 16, 8)` [**16** spt, not 17]. Maybe this is problem and not 3.51m ?

My disk is definitely 17 sectors per track, I just checked with the `s4disk` program from the s4 tools.
The current code should ignore the values in the init call if you have supplied a disk label, either with the diagnostic disk, or with the `makehdimg` program I added.

In any case, I put a disk image up where you (plural) can get to it, so you can experiment directly if you want.

I will also make Jesse's change and see if that makes a difference. I will do that first, since it's quick.

**Comment by arnoldrobbins** [comment]
Jesse's change got rid of the panic but the kernel still wouldn't boot; lots of memory map errors.

I managed to setup a disk with just 16 sectors per track (1400 cylinders x 16 heads). I didn't put a boot loader on it, but using the ICUS disk I booted off of it and 3.51m does come up!  Truly strange.

Using 16 sectors per track instead of 17 reduces the disk to 175 meg from not quite 186 Meg. I suppose we could live with that in order to have the FIXDISK 2.0 installed.  But it's still kinda weird.  That's all for now. :-)

**Comment by agentbooth** [comment]
I was looking into a little today also -- seems like my issue is that I previously made an image 1400x16(heads)x16(sec/tk)x512, but then formatted with 17 sec/tk, so the geom in the header says 17 sec/tk. Previously I would just load with `wd2010_init(..., 512, 16, 16)` and the cylinders would be calculated from the file size (1400).  I just tried doing the equivalent with `result = wd2010_default_init(ctx, fp, drivenum, secsz, 16, 16);` and the old image loaded fine. So probably just that 16 sec/tk vs 17 sec/tk inconsistency causing me issues now. If I originally created the image file as 1400x16x17x512, it might have been fine.

**Comment by agentbooth** [comment]
One other note -- I checked the /usr/lib/iv entries, and all the hard drives use 17sec/tk so seems like what we should be using for hd.img creation -- though i suppose anything should work as long as it's initialized with the right geom.

**Comment by agentbooth** [comment]
Interesting -- @arnoldrobbins, I downloaded your image, used the loading command `result = wd2010_default_init(ctx, fp, drivenum, secsz, 17, 16);` (I probably could have just let it use the wd2010_disk_label_init) and logged into the system. I found your FIXDISK2.0 and installed it via user agent, and install looked to work fine. I shutdown, then restarted the emulator, and sure enough it hung on boot. This is where it hung in the startup log:
...
src/memory.c:441:IoWrite(): TCR (496000) Line 1 A-lead set: off
src/memory.c:433:IoWrite(): TCR (494000) Line 1 hold set: off
src/memory.c:437:IoWrite(): TCR (495000) Line 2 hold set: off
src/memory.c:429:IoWrite(): TCR (493000) Hook relay 2 set: off
src/memory.c:445:IoWrite(): TCR (497000) Line 2 A-lead set: off
unhandled write16, addr=0x004F0000, data=0x00000000
src/memory.c:489:IoWrite(): dialer reg low byte (4B0400) now: 0
src/memory.c:497:IoWrite(): dialer reg high byte (4B0800) now: 0
src/memory.c:624:IoWrite(): ROMLMAP (E43000): 1
src/memory.c:624:IoWrite(): ROMLMAP (E43000): 1
src/memory.c:605:IoWrite(): EE+ (E40000): 0
src/memory.c:616:IoWrite(): PIE+ (E41000): 0
src/memory.c:624:IoWrite(): ROMLMAP (E43000): 1

The usual '*******' didn't appear under the "Searching hard disk..." so can't find the boot loader?
![after fixdisk2](https://user-images.githubusercontent.com/62037742/103487304-491c6280-4dd2-11eb-828f-1c56351b5420.png)
Not sure what's going on here.

**Comment by philpem** [comment]
That's making me suspicious of disk corruption. I don't think FIXDISK2 replaces the loader, just the kernel.

I'd be tempted to turn on the printf's in the WD2010 emulation core and see if the CHS -> byte address mapping is being done correctly.

The other question is whether the FIXDISK2 image is correct.

**Comment by shadyjesse** [comment]
Actually, looks like I do get some *****'s after "Searching hard disk" but then it starts again, and shows the above screen. I'm wondering if it's anything related to the P5.1 detection (and >8 heads?) and 3.51m -- as that log stops suspiciously around where the revlev detection is occurring. In a regular 3.51 boot, it's something like:
...
src/memory.c:489:IoWrite(): dialer reg low byte (4B0400) now: 0
src/memory.c:497:IoWrite(): dialer reg high byte (4B0800) now: 0
src/memory.c:624:IoWrite(): ROMLMAP (E43000): 1
src/memory.c:624:IoWrite(): ROMLMAP (E43000): 1
src/memory.c:605:IoWrite(): EE+ (E40000): 0
src/memory.c:616:IoWrite(): PIE+ (E41000): 0
src/memory.c:605:IoWrite(): EE+ (E40000): 1
src/memory.c:616:IoWrite(): PIE+ (E41000): 1
src/memory.c:616:IoWrite(): PIE+ (E41000): 0
src/memory.c:616:IoWrite(): PIE+ (E41000): 1

those writes to PIE+ are used to check that the PIE+ (bit 10) gets mirrored to bit 15 in the GSR for P3 revlev detection. I'll keep investigating.

**Comment by agentbooth** [comment]
I was **unable** to repro with a big disk, fresh install + FIXDISK2.0.
Steps I took:
1. `makehdimg -h 16 -c 1400 -b 17`
2. initialized with standard diagnostics disk (1400 cyl, 16 heads, 17 sec/trk)
3. did 12 disk install
4. split FIXDISK2.0+IN.gz into two files, copied over via MS-DOS floppy, cat'd together, copied over gzip, uncompressed, moved to /usr/spool/uucppublic, installed in ua
5. shutdown
6. restarted, and booted normally...

(This test included the line fix:
`ctx->data[drivenum] = malloc(ctx->geometry[drivenum].geom_secsz * ctx->geometry[drivenum].geom_spt);`)

**Comment by arnoldrobbins** [comment]
After redoing the disk image this went away. Closing the issue.
