### ISSUE TITLE
How, EXACTLY, do I access a DOS disk image?

### ISSUE THREAD

**Issue by KedalionDaimon** [philpem/freebee#37]
Hi!

I saw the documentation talk of something called "discim", but I could not figure out how, EXACTLY, I can transfer files in and out of the emulator. As user "install", there is something called "Floppydisk" in a menu, and there is "MSDOS Disk Read" as a submenu, and I cannot get it to work...

Is this even the correct way to try? Or do I log in as root and somehow use the mount command? EDIT: I discovered the msdos command you mentioned, and ran it as root, but nothing seems to happen - it simply tells me there is, effectively, no floppy! I do not get how to use F11, it does nothing noticeable...

Thank you in advance for your kind help and for this awesome emulator!

**Comment by KedalionDaimon** [comment]
Never mind, I figure it out, and in case anyone wonders:

1. Get some old 360 kb DOS floppy image from the web (or make it yourself).
2. Use DOSBOX' imgmount-command to access the disk image (erasing its original content and putting in your own). When done, leave DOSBOX.
3. The resulting floppy image will contain "whatever you want". Things you might get quickly are tar, gzip, compress and uncompress in order to handle the 3B1 stuff you will find around the web, so start placing THESE into your system.
4. Name the image "discim". That is: NOT discim.img, just really exactly "discim".
5. Place it in the same folder as freebee. Just the executable freebee, i.e. not in some sub-folder, but "right next to freebee".
6. Press F11 to "make it available".
7. In freebee's Unix terminal, type "msdos" and press Enter.
8. Use the COPY function to copy stuff out of the image and into the file system. Then CLOSE the whole thing. (Referring here to your Unix menus.)
9. Press again F11 to "make the image unavailable". (Which allows you to erase "discim", put there ANOTHER disk image, call it "discim", and make it in turn available by pressing F11 and then typing "msdos".)
10. Once you are done with everything, DELETE the discim file, so you have no issues on reboot (which sometimes was hanging with an existing discim-file present).

As a matter of fact, I this way transferred the binary distribution of Austin Kyoto Common Lisp (akcl) to my emulator and I am DELIGHTED! :) Thank you so much for making this wonderful emulator. If in any way my "idiot-proof" steps above seem helpful, consider please adding them to your documentation.

Other than that: any chance to get the window resizable? Mini vMac solves it by allowing you to say, one "virtual" pixel is four "real" pixels... Ubuntu 20.04, anyway, does NOT allow resizing. If I want it "bigger" I can only lower my desktop resolution.

**Comment by agentbooth** [comment]
Glad you got things working! That is a good point about needing to remove the `discim` file to prevent boot issues next time running the emulator. Recently a command line option was added for scaling -- you could try playing with that. The usage is: "-s xscale:yscale" on the command line. So something like "-s 2:3" will make the aspect ratio more like the original Unix PC. The frame buffer is pretty widescreen (720x348) but was mapped to a standard 4:3 CRT, so horizontally compressed, vertically stretched. Or you could just do "-s 2:2" to double the screen size.

@philpem how about renaming `discim` to `floppy.img`?

**Comment by KedalionDaimon** [comment]
@shadyjesse : THANK YOU SO VERY, VERY MUCH! - That thing with "-s" works _awesomely_, particularly given that I can give fractional resizing values, and that makes it possible to fill out my entire screen and "let it look as if this is my main OS". :)

Actually, the final look reminded me of this, which you likely know anyway, and where one needs to check is it LVDS-0 or LVDS-1:

sudo xrandr --output LVDS-1 --gamma 0.001:1.000:0.001 --brightness 1.0

(you set it back with this:

sudo xrandr --output LVDS-1 --gamma 1.000:1.000:1.000 --brightness 1.0

)

**Comment by agentbooth** [comment]
@KedalionDaimon glad it worked for you and you were able to play around with akcl! :+1:
