### ISSUE TITLE
Setting base_memory to 512 and extended_memory to 0 results in trouble booting

### ISSUE THREAD

**Issue by agentbooth** [philpem/freebee#47]
When configuring a system with only 512K RAM, I am usable to boot to login. This was tested using David Gesswein's VCF disk image with the 3.51m kernel. Upon startup it states 315392 available memory (from the 524288 total memory listed). When setting to 1024K RAM, the system boots fine.

The system attempts to load but asserts during "loading drivers" or "setting up screen" in the attempts I've made: 
`freebee: src/memory.c:1063: m68k_read_memory_8: Assertion 'address != 0xFFFF01' failed.`
indicating Musashi m68ki_exception_bus_error() triggered the condition. Musashi says this occurs when a bus error occurs when we were already processing a bus error, address error, or reset, this is a catastrophic failure.  

Perhaps the system is running out of memory and attempts to swap? The swap size for that hard drive image looks to be the default 5000k. (Though I don't know how to confirm the 5MB swap is being used.) In normal operation with 4MB RAM, I assume we never need to swap. Perhaps it's something related to memory handling and attempting to swap to hard drive? There is some interplay between different type of page table entries (PTEs) that I don't fully understand:
pte/htpe: MAP RAM (where we update the page status bits in mapAddr() )
mpte: pte's in RAM, used by the OS
fpte: pte's in disk

from sys/pte.h:
/*
 * Incore page table entry
 *
 * There are two major kinds of pte's: those which have ever existed (and are
 * thus either now in core or on the swap device), and those which have
 * never existed, but which will be filled on demand at first reference.
 * There is a structure describing each.  There is also an ancillary
 * structure used in page clustering.
 */

/*      The format of a pte in the map  */
struct pte
{
        ushort     pt_wp:1,             /* write permission     */
                  pt_acc:2,             /* access status        */
                        :3,             /* non h/w flags */
                pt_pfnum:10;            /* core page frame number */
};

/*      The format of a pte in memory (our RAM) */
struct mpte
{
        ushort  pg_ipte;                /* index of hardware pte */
        ushort  pt_wp:1,                /* write permission     */
                pg_acc:2,               /* access control */
                pg_fod:1,               /* is fill on demand (=0) */
                pg_swapm:1,             /* have to write back to swap */
                pg_pageo:1,             /* page is being paged out */
                pg_pfnum:10;            /* core page frame number or 0 */
};
struct fpte
{
        ushort  pg_blkno;               /* file system block number */
        ushort  pt_wp:1,                /* write permission     */
                pg_acc:2,               /* access control */
                pg_fod:1,               /* is fill on demand (=0) */
                pg_swapm:1,             /* have to write back to swap */
                pg_pageo:1,             /* page is being paged out */
                pg_last:1,              /* last data page */
                pg_lastsec:2,           /* disk sectors in the last data page*/
                pg_fileno:7;            /* file no for the page */
};

This issue can be worked around by setting base memory to 1024.

**Comment by agentbooth** [comment]
Call stack on current attempt:
m68k_read_memory_8 (0x00ffff01); // bus error within bus error
m68ki_exception_bus_error ()
m68k_pulse_bus_error ()  [Page fault?]
m68k_read_memory_8 (0x2FFD86)

From musashi:
```
/* Exception for bus error */
static inline void m68ki_exception_bus_error(void)
{
    int i;

    /* If we were processing a bus error, address error, or reset,
     * this is a catastrophic failure.
     * Halt the CPU
     */
    if(CPU_RUN_MODE == RUN_MODE_BERR_AERR_RESET)
    {
m68k_read_memory_8(0x00ffff01);
        CPU_STOPPED = STOP_LEVEL_HALT;
        return;
    }
    CPU_RUN_MODE = RUN_MODE_BERR_AERR_RESET;
...
```

**Comment by philpem** [comment]
Are you sure this is a supported configuration?

I think 3.50 was the only UNIX which could boot on 512k machines (the 7300 specifically). All 3B1s came with 1MB minimum, and (don't quote me on this!) the 3.51 UNIX.

**Comment by agentbooth** [comment]
Ahh this could definitely be the issue -- running out of RAM trying to boot a 3.51 UNIX.  If I can find an older OS set, I could try that on the 512k, but it sounds like this is Not A Bug then.

**Comment by agentbooth** [comment]
I've spent a lot of time investigating this issue, as I was getting the "double bus error" assert in other instances. My conclusion is that the handling in Musashi is incorrect. On the UNIX PC, there are instances when a page fault will occur *during* the bus error exception handling of an initial PF. Musashi interprets this as a catastrophic error. However, the only time it's catastrophic is if the bus error occurs during the setup of the stack frame. And the stack frame is setup within m68ki_exception_bus_error() so this should never occur. MAME's Musashi code appears to have been changed to reflect this.

I'll see if I can get Musashi updated with a fix, and then update Freebee to the latest Musashi submodule if that sounds good.

**Comment by philpem** [comment]
Sounds good to me!

**Comment by agentbooth** [comment]
One other quick note (on the original issue), I tried setting the the RAM to 512KB and booting 3.51m with the check for double bus fault disabled in Musashi and sure enough things booted and seemed to work fine. Memory was nearly 100% used and seemed to be hitting the swap file as it was fairly slow, but did seem to work.

**Comment by agentbooth** [comment]
Fixed with latest Musashi
