### ISSUE TITLE
Running freebee help

### ISSUE THREAD

**Issue by MidnightThunder** [philpem/freebee#50]
I don't understand all this compiling and makefile stuff. How can I get the latest prebuilt version that will run on 32bit windows. (I should be able to install the OS by myself).

**Comment by philpem** [comment]
We don't distribute prebuilt binaries for Windows, sorry. You could build it with Mingw32 and MSYS, though I haven't done that in quite some time. The main development platform for Freebee is Linux, though I think someone has successfully run it under Mac OS X.

**Comment by philpem** [comment]
If you have a Raspberry Pi, you could install Raspbian and run Freebee on it.
These commands will build Freebee:
```
git clone https://github.com/philpem/freebee.git
cd freebee
make
./freebee
```
