### ISSUE TITLE
Add configuration file support

### ISSUE THREAD

**Issue by philpem** [philpem/freebee#9]
Configuring the emulator currently requires editing hard-coded sections of code and recompiling. This is inflexible and annoying.

Freebee should use a configuration file to set up the emulator. This could be, for example, a YAML file. If YAML were used, Libcyaml could be used to parse it:

* https://github.com/tlsa/libcyaml
* https://github.com/tlsa/libcyaml/blob/master/docs/guide.md
* https://github.com/tlsa/libcyaml/tree/master/examples

As a minimum, the following should should be configurable:

* Amount of memory (base and expansion)
* Hard disc geometry and filename (if raw binary file)
* Floppy disc filename and optional geometry
  * Geometry only needed for raw binary files
  * Optional: add support for a 'floppy disc list' and next/prev buttons (e.g. altF11 next, shiftF11 prev) in the emulator interface. This would make installing UNIX easier.

**Comment by philpem** [comment]
One more thing which should be configurable now #12 is in - VIDPAL on/off.

Motherboard type (P5/P5.1) too.

**Comment by arnoldrobbins** [comment]
@philpem Please see PR #43 which adds configuration support for the vidpal, the amounts of memory, and the default sectors per track and number of cylinders for hard disks.  I could not figure out how to set P5 vs. P5.1 but IMHO that's not necessary.  I don't know what to do about floppy geometry; the current setup seems to work OK out of the box. If you merge #43 maybe you can then close this issue. :-)   Thanks!
